### ISSUE TITLE
Different id ?

### ISSUE THREAD

**Issue by abdelouahabb** [keygen-sh/py-machineid#15]
Hi,
Does the library gives another id, as the command 

`subprocess.check_output('wmic csproduct get uuid').decode("utf-8").split('\n')[1].strip()`

Does not give the same value as `uniqueid.id()`

**Comment by loicreynier** [comment]
As you can see [here](https://github.com/keygen-sh/py-machineid/blob/dab8f27f7c1e1bffb86aacd1d3ccd1957adf4504/machineid/__init__.py#L74C1-L74C1), the library execute the following command 

```python
id = __exec__('wmic csproduct get uuid').split('\n')[2].strip()
```

**Comment by abdelouahabb** [comment]
> As you can see [here](https://github.com/keygen-sh/py-machineid/blob/dab8f27f7c1e1bffb86aacd1d3ccd1957adf4504/machineid/__init__.py#L74C1-L74C1), the library execute the following command
> 
> ```python
> id = __exec__('wmic csproduct get uuid').split('\n')[2].strip()
> ```

Here is what I get, I just removed the library and reinstall it again to double check :

In [3]: machineid.id()
Out[3]: '9d132cc8-*********************'

In [4]: subprocess.check_output('wmic csproduct get uuid').decode("utf-8").split('\n')[1].strip()
Out[4]: '0DF2A2FD-*********************'

**Comment by ezekg** [comment]
It may pulling from [the registry](https://github.com/keygen-sh/py-machineid/blob/dab8f27f7c1e1bffb86aacd1d3ccd1957adf4504/machineid/__init__.py#L69). Try this instead:

```py
machineid.id(winregistry=False)
```

**Comment by abdelouahabb** [comment]
> ```python
> machineid.id(winregistry=False)
> ```

Works perfectly,
But why it does take more time ?

```
python -mtimeit -s'import machineid' 'machineid.id()'
10000 loops, best of 5: 26.7 usec per loop
python -mtimeit -s'import machineid' 'machineid.id(winregistry=False)'
1 loop, best of 5: 973 msec per loop
```

**Comment by ezekg** [comment]
Because accessing the registry is fast and WMI is slow, which is why the registry is the default.
