### ISSUE TITLE
Will the ID change if the system is reinstalled

### ISSUE THREAD

**Issue by ryjfgjl** [keygen-sh/py-machineid#22]
Will the ID change if the system is reinstalled？

**Comment by ezekg** [comment]
Typically, yes. When you install/reinstall an operating system, that's typically when it writes the system GUID. You may want to look into hardware fingerprinting, which isn't something that this package handles.

E.g. get the serial numbers of the GPU, CPU, HDD, mobo, etc. and hash them.
