### ISSUE TITLE
powershell popup in windowed application

### ISSUE THREAD

**Issue by crankedguy** [keygen-sh/py-machineid#5]
As discussed shortly already using plain powershell leads to nasty popups of powershell windows if this is called by windowed applications, i.e. not started from a shell. This is per powershell design and cannot be handled via powershell itself.

A solution however is possible through python, although I did not test if this is also possible with your command as you are invoking a shell specifically, which is not necessary.
Aside from that creationflags=subprocess.CREATE_NO_WINDOW will prevent creating popups even in windowed applications.
A code like that will work :

```
return subprocess.run(cmd,
                              shell=False,
                              capture_output=True,
                              check=True,
                              encoding="utf-8",
                              creationflags=subprocess.CREATE_NO_WINDOW).stdout
```

**Comment by ezekg** [comment]
I am not able to reproduce this on Windows 10, nor on WSL2. The package uses [`shell=True`](https://github.com/keygen-sh/py-machineid/blob/master/machineid/__init__.py#L37), which [already prevents this](https://stackoverflow.com/a/7509054).

If possible, can you record a video of this occurring using the latest version of py-machine?

**Comment by crankedguy** [comment]
Ah sorry you can close this I did not know that shell=True handles this magically implicitely. Out of habit shell=True is only used here when not possible otherwise due to security implications, and this is practically never. That is why you don't see it, and we got it.

Python 3.7 is 5 years old and EOL, meaning it does not even get critical fixes anymore since a few days. 
Using this in context with security applications... but everyones mileage varies,..
