### ISSUE TITLE
Syntax warning because of "\S" in Python 3.12

### ISSUE THREAD

**Issue by benoit9126** [keygen-sh/py-machineid#9]
Hi!

When I import your package using Python 3.12, a syntax warning is emitted. 

```pycon
>>> import machineid
/home/user/.pyenv/versions/venv-name/lib/python3.12/site-packages/machineid/__init__.py:70: SyntaxWarning: invalid escape sequence '\S'
  id = __reg__('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography', 'MachineGuid')
```

This is related to this PR of CPython python/cpython#99011. Could it be possible to add a `r` before this string to avoid this warning (that will become a `SyntaxError` in future Python releases)

```python
id = __reg__(r"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography", "MachineGuid")
```

**Comment by ezekg** [comment]
Would you be open to a PR?

**Comment by benoit9126** [comment]
Sure!
